source 'https://github.com/CocoaPods/Specs.git'

target 'CheeseBug', :exclusive => true do
  pod "CheeseBug", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CheeseBug", :path => "../"

  
end
