source 'https://github.com/CocoaPods/Specs.git'
# source 'https://pedrohperalta@bitbucket.org/pedrohperalta/specs.git'

target 'NotifiCrash', :exclusive => true do
  pod "NotifiCrash", :path => "../"
  pod "KeepLayout", :git => "https://github.com/iMartinKiss/KeepLayout.git", :tag => "v1.6.0"
end

target 'Tests', :exclusive => true do
  pod "NotifiCrash", :path => "../"
end
